# Generated by Django 4.2.2 on 2023-06-18 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='media/docs', verbose_name='Файл')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('is_checked', models.BooleanField(default=False)),
                ('is_paied', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата публикации')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL, verbose_name='Агент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-pub_date',),
            },
        ),
    ]
