# Generated by Django 4.2.2 on 2023-07-30 16:10

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, validators=[core.validators.check_inn], verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=12, validators=[core.validators.check_inn], verbose_name='ОГРН(ОГРИП)')),
                ('pub_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата создания')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('surname', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('inn', models.CharField(max_length=12, validators=[core.validators.check_inn], verbose_name='ИНН')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('email', models.CharField(validators=[django.core.validators.EmailValidator], verbose_name='Email')),
                ('bank', models.CharField(choices=[('tinkoff', 'Тинькофф'), ('gpb', 'ГПБ'), ('sber', 'Сбер'), ('alfa', 'Альфабанк')], verbose_name='Банк')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('status', models.CharField(choices=[('in_work', 'в работе'), ('in_process', 'орабатывается банком'), ('duble', 'дубль'), ('sending_to_bank', 'отправка в банк'), ('deny', 'отказано'), ('success', 'подтверждено банком')])),
                ('is_need_visit_service', models.BooleanField(blank=True, default=False)),
                ('is_paied', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата создания')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='Агент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-pub_date',),
            },
        ),
    ]
