# Generated by Django 4.2.2 on 2023-08-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_order_options_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank',
            field=models.CharField(choices=[('tinkoff', 'Тинькофф'), ('gpb', 'ГПБ'), ('sber', 'Сбер'), ('alfa', 'Альфабанк')], default='в работе', verbose_name='Банк'),
        ),
    ]
