# Generated by Django 4.2.2 on 2023-08-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_order_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank',
            field=models.CharField(choices=[('tinkoff', 'Тинькофф'), ('gpb', 'ГПБ'), ('sber', 'Сбер'), ('alfa', 'Альфабанк')], verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_work', 'в работе'), ('in_process', 'обрабатывается банком'), ('duble', 'дубль'), ('sending_to_bank', 'отправка в банк'), ('deny', 'отказано'), ('success', 'подтверждено банком')], default='в работе'),
        ),
    ]
