# Generated by Django 4.2.2 on 2023-08-01 18:46

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_order_bank_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='inn',
            field=models.CharField(max_length=12, validators=[core.validators.check_inn], verbose_name='ИНН'),
        ),
    ]
