# Generated by Django 4.2.2 on 2023-08-04 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_order_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_need_visit_service',
            field=models.BooleanField(verbose_name='Нужен выездной сервис'),
        ),
    ]
