# Generated by Django 4.2.2 on 2023-08-04 18:12

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_order_email_alter_order_is_need_visit_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(validators=[core.validators.isValidEmail], verbose_name='Email'),
        ),
    ]
