# Generated by Django 4.2.2 on 2023-09-24 14:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank',
            field=models.CharField(choices=[('Тинькофф', 'Тинькофф'), ('ГПБ', 'ГПБ'), ('Сбер', 'Сбер'), ('Альфабанк', 'Альфабанк')], verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в работе', 'в работе'), ('обрабатывается банком', 'обрабатывается банком'), ('дубль', 'дубль')], default='в работе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.CharField(max_length=12, unique=True, validators=[core.validators.check_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ogrn',
            field=models.CharField(blank=True, max_length=12, unique=True, validators=[core.validators.check_inn], verbose_name='ОГРН(ОГРИП)'),
        ),
    ]
