# Generated by Django 4.2.2 on 2023-10-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_order_bank_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_looked',
            field=models.BooleanField(default=False),
        ),
    ]
