# Generated by Django 4.2.2 on 2024-02-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в работе', 'в работе'), ('обрабатывается банком', 'обрабатывается банком'), ('дубль', 'дубль'), ('завершено', 'завершено')], default='в работе'),
        ),
    ]
