# Generated by Django 4.2.2 on 2024-02-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_order_date_update_alter_order_pub_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceByBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('Тинькофф', 'Тинькофф'), ('ГПБ', 'ГПБ'), ('Сбер', 'Сбер'), ('Альфабанк', 'Альфабанк')], verbose_name='Банк')),
                ('price', models.IntegerField(verbose_name='Вознаграждение')),
            ],
        ),
    ]
