# Generated by Django 4.2.2 on 2024-02-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_pricebybank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricebybank',
            options={'verbose_name_plural': 'Вознаграждение банка'},
        ),
        migrations.RemoveField(
            model_name='pricebybank',
            name='price',
        ),
        migrations.AddField(
            model_name='pricebybank',
            name='price10',
            field=models.IntegerField(default=1000, verbose_name='Вознаграждение до 10'),
        ),
        migrations.AddField(
            model_name='pricebybank',
            name='price5',
            field=models.IntegerField(default=1000, verbose_name='Вознаграждение до 5'),
        ),
        migrations.AddField(
            model_name='pricebybank',
            name='price_largest',
            field=models.IntegerField(default=1000, verbose_name='Вознаграждение свыше 10'),
        ),
    ]
