# Generated by Django 5.0.6 on 2024-06-28 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_order_date_update_alter_order_pub_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=150, unique=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Группы вопросов',
            },
        ),
      
    ]
