# Generated by Django 5.0.6 on 2024-06-28 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_questgroup_questions_alter_order_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='father_name',
            field=models.CharField(blank=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organization',
            field=models.CharField(verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.CharField(verbose_name='Фамилия'),
        ),
      
    ]
