# Generated by Django 5.0.6 on 2024-06-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_questions_testsscore_testsscore_unique_user_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
