# Generated by Django 5.0.6 on 2024-06-28 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_delete_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(verbose_name='Вопрос')),
                ('right_answer', models.CharField(verbose_name='Правильный ответ')),
                ('wrong_answer1', models.CharField(verbose_name='Ошибка1')),
                ('wrong_answer2', models.CharField(verbose_name='Ошибка2')),
                ('wrong_answer3', models.CharField(verbose_name='Ошибка3')),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='service.questgroup')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
