# Generated by Django 5.0.6 on 2024-06-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_alter_questions_group_alter_testsscore_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsscore',
            name='group',
        ),
    ]
