# Generated by Django 5.0.6 on 2024-06-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_remove_testsscore_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsscore',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='testsscore',
            name='unique_user_group',
        ),
    ]
