# Generated by Django 5.0.6 on 2024-06-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_alter_testsscore_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsscore',
            options={'verbose_name_plural': 'Количество правильных ответов'},
        ),
    ]
