# Generated by Django 5.0.6 on 2024-06-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_alter_testsscore_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsscore',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='service.questgroup', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
