# Generated by Django 5.0.6 on 2024-06-28 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_testsscore_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(verbose_name='Вопрос')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='service.questgroup')),
            ],
            options={
                'verbose_name_plural': 'Вопросики',
            },
        ),
    ]
