# Generated by Django 5.0.6 on 2024-06-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='group',
        ),
    ]
