# Generated by Django 5.0.6 on 2024-06-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_remove_questions_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='service.questgroup'),
            preserve_default=False,
        ),
    ]
