# Generated by Django 5.0.6 on 2024-07-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_testsscore_unique_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_how_answered',
            field=models.BooleanField(default=False, verbose_name='How answered'),
        ),
        migrations.AddField(
            model_name='questions',
            name='is_touched',
            field=models.BooleanField(default=False, verbose_name='Touched'),
        ),
    ]
