# Generated by Django 5.0.6 on 2024-07-23 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_questions_is_how_answered_questions_is_touched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='is_how_answered',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='is_touched',
        ),
        migrations.CreateModel(
            name='UserQuestAnswered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_touched', models.BooleanField(default=False, verbose_name='Touched')),
                ('is_how_answered', models.BooleanField(default=False, verbose_name='How answered')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='service.questions', verbose_name='Пройденный вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quest_answered', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Пройденные вопросы',
            },
        ),
        migrations.AddConstraint(
            model_name='userquestanswered',
            constraint=models.UniqueConstraint(fields=('user', 'quest'), name='unique_user_quest'),
        ),
    ]
