# Generated by Django 5.0.6 on 2024-07-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_remove_questions_is_how_answered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestanswered',
            name='is_touched',
        ),
    ]
